name: Cloud DevOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display repository
        run: ls -la

      - name: Check Git
        run: git --version

      - name: Validate project
        run: echo "Validation successful"

      - name: Show commit SHA
        run: echo "${{ github.sha }}"

      - name: Show branch
        run: echo "${{ github.ref }}"